### ISSUE TITLE
Windows build failing - problem with iconv lib

### ISSUE THREAD

**Issue by justedni** [melonDS-emu/melonDS#2342]
Hello!

I've noticed that the Windows build has been failing for a bit more than a week, with the following error:

> D:/a/_temp/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/15.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find /ucrt64/lib/libiconv.dll.a: No such file or directory

I'm working on a fork so I'm getting the same error, I'd love to help you solve the issue, but I might need a bit more information, I don't fully understand what's going on here. The "iconv" lib doesn't seem to be directly referenced in the cmake files (the only file that mentions it is flake.nix), maybe it's a "hidden" dependency inside another lib dependency? And maybe it started failing recently because that library has been automatically updated?
This could be some kind of path problem. `/ucrt64/lib/libiconv.dll.a` looks like a unix-formatted path, but we're on Windows, shouldn't it be something like `D:/a/_temp/msys64/ucrt64/lib/libiconv.dll.a` ? Maybe the path got hard-coded the wrong way in a recent update.

Thanks in advance!
Vincent

**Comment by vitor251093** [comment]
UPDATE: We managed to fix the issue in our fork by doing this:
https://github.com/vitor251093/KHMelonMix/commit/e21336cfaddc0e8c15c2b39212d25c77d552cd66

The credits of this implementation goes to @ag-advania's melonPrimeDS

I believe this part is the only thing that is truly necessary for the fix though:
```
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: false
        path-type: inherit
        pacboy: gcc:p cmake:p ninja:p make:p
```
